server:
  port: 8045
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: web-all
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    base-url: http://192.168.41.101:9411/
    sender:
      type: web
