server:
  port: 9000

spring:
  application:
    name: service-item
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  zipkin:
    base-url: http://192.168.41.101:9411/
    sender:
      type: web
  redis:
    port: 6379
    host: 192.168.41.101
    password: wg199710
app:
  thread-pool:
    corePoolSize: 4
    maximumPoolSize: 8
    queueSize: 2000
    keepAliveTime: 300
