server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://192.168.41.101:3306/gmall_product?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  zipkin:
    base-url: http://192.168.41.101:9411/
    sender:
      type: web
